# gradle/libs.versions.toml

[versions]
agp = "8.9.1"
kotlin = "2.1.20"

# AndroidX Core and AppCompat
core-ktx = "1.16.0"
appcompat = "1.7.0"
recyclerview = "1.4.0"
paletteKtx = "1.0.0"

# Android Lifecycle
lifecycle-extensions = "2.2.0"
lifecycle-viewmodel-ktx = "2.8.7"

# Navigation
navigation-fragment-ktx = "2.8.9"
navigation-ui-ktx = "2.8.9"
navigation-testing = "2.8.9"

# Work Manager
work-runtime-ktx = "2.10.0"

# ConstraintLayout
constraintlayout = "2.2.1"
constraintlayout-compose = "1.1.1"

# Compose Versions
activity-compose = "1.10.1"
compose-android = "1.7.8"
compose-material = "1.7.8"
compose-animation = "1.7.8"
compose-ui = "1.8.0"
compose-foundation = "1.7.8"
compose-ui-tooling = "1.7.8"

# Other Libraries
commons-text = "1.13.1"
gson = "2.13.0"
biometric-ktx = "1.4.0-alpha02"

# AndroidX Test Libraries
espresso = "3.6.1"
test-core-ktx = "1.6.1"
test-runner = "1.6.2"
test-rules = "1.6.1"
fragment-testing = "1.8.6"
ui-test-junit4 = "1.7.8"
ui-test-manifest = "1.7.8"

[libraries]
# Core Libraries
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
palette-ktx = { group = "androidx.palette", name = "palette-ktx", version.ref = "paletteKtx" }

# Android Lifecycle
lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }

# Navigation
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation-ui-ktx" }
navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigation-testing" }

# Work Manager
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-runtime-ktx" }

# ConstraintLayout
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }

# Compose
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "compose-android" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose-material" }
compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "compose-animation" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose-foundation" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui-tooling" }

# Miscellaneous Libraries
commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "commons-text" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
biometric-ktx = { group = "androidx.biometric", name = "biometric-ktx", version.ref = "biometric-ktx" }

# Testing Libraries
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso" }
espresso-idling-resource = { group = "androidx.test.espresso", name = "espresso-idling-resource", version.ref = "espresso" }
test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "test-core-ktx" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "test-runner" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "fragment-testing" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "ui-test-junit4" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "ui-test-manifest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }