blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: Organization wide discussions
    url: https://github.com/orgs/HeAndroids2Much/discussions
    about: For any discussion within our community
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
  - name: Email Me
    url: mailto://wayne6324@proton.me
    about: Contact me via sending email